class ROLES:
    SUPER_ADMIN = 1
    ADMIN = 2
    SALES_MANAGER = 10
    INVENTORY_MANAGER = 11
    CRM_MANAGER = 12
    HR_MANAGER = 13
    FINANCE_MANAGER = 14
    QUALITY_MANAGER = 15
    LOGISTICS_MANAGER = 16
    PRODUCTION_MANAGER = 17
    PROCUREMENT_MANAGER = 18
    PLANT_MANAGER = 19
    SALES_REP = 20
    USER = 99