
from enum import IntEnum
class ROLES(IntEnum):
    SUPER_ADMIN = 1        # ← 0 kar de (standard)
    ADMIN = 2
    MANAGER = 3
    SALES_MANAGER = 4
    INVENTORY_MANAGER = 5
    CRM_MANAGER = 6
    HR_MANAGER = 7
    FINANCE_MANAGER = 8
    QUALITY_MANAGER = 9
    LOGISTICS_MANAGER = 10
    PRODUCTION_MANAGER = 11
    PROCUREMENT_MANAGER = 12
    PLANT_MANAGER = 13
    SALES_REP = 14
    USER = 99